apiVersion: dapr.io/v1alpha1
kind: MCPServer
metadata:
  name: agent-mcp
spec:
  endpoint:
    streamableHTTP:
      url: http://inventory-events-publisher-reaction.drasi-system.svc.cluster.local:8000/mcp
