apiVersion: dapr.io/v1alpha1
kind: MCPServer
metadata:
  name: my-mcp-server
spec:
  endpoint:
    streamableHTTP:
      url: http://localhost:3500/v1.0/invoke/inventory-events-publisher-DaprAgentRouter.drasi-system/method/mcp
